// Generate docs/reason-codes.md — the deny-reason LEGEND — from the reason registry (src/reasons.ts).
// Run via `npm run reason-codes` (vite-node). Output is DETERMINISTIC (no timestamps), so CI can
// regenerate and `git diff --exit-code` it: the legend can never drift from the codes the guard emits.
//
// Two enforcement directions, together making the legend's completeness true by construction:
//  - a code added to the registry but not regenerated here → the committed doc is stale → CI diff RED
//    (and every emitted code is IN the registry by S1's typed partitions + static check);
//  - a legend row hand-added here → regeneration erases it (the registry is the sole source) → diff RED;
//  - a registry entry that is never actually emitted in src/ → the emission-presence test (reasons.test)
//    goes RED. So neither "emitted code with no legend row" nor "legend row with no emitting code" can ship.
//
// Do not edit docs/reason-codes.md by hand.
import { writeFileSync } from "node:fs";
import { REASONS, type ReasonWhen } from "../src/reasons.js";

const OUTPUT = "docs/reason-codes.md";

/** The lifecycle groups, in the order a user meets them. Each `when` value from the registry maps here. */
const GROUPS: { when: ReasonWhen; title: string; blurb: string }[] = [
  { when: "policy-load", title: "At policy load", blurb: "You see these while loading or parsing your policy file (before any payment)." },
  { when: "payment", title: "At payment time", blurb: "You see these when the guard evaluates a payment — a verdict, or a problem parsing the server's challenge/authorization." },
  { when: "read-api", title: "From a read API", blurb: "You see these from a read-only method such as `snapshot()`." },
];

function main(): void {
  const codes = Object.entries(REASONS);
  // Escape any `|` in cell text so it renders as a literal pipe, not a column break (codes and
  // fix-text legitimately contain "chain|token").
  const cell = (s: string): string => s.replace(/\|/g, "\\|");
  const sections = GROUPS.map(({ when, title, blurb }) => {
    const rows = codes
      .filter(([, m]) => m.when === when)
      .sort(([a], [b]) => (a < b ? -1 : 1))
      .map(([code, m]) => `| \`${cell(code)}\` | ${cell(m.means)} | ${cell(m.fix)} |`);
    return [`## ${title}`, "", blurb, "", "| Code | What it means | What to change |", "|------|---------------|----------------|", ...rows, ""].join("\n");
  });

  const out = [
    "<!-- GENERATED by scripts/gen-reason-codes.ts from src/reasons.ts — do not edit by hand. -->",
    "",
    "# Reason codes",
    "",
    "Every decision the guard makes carries a stable machine `reason` code. When a payment is denied —",
    "or a policy won't load — this table says what the code means and what to change. Codes are grouped",
    "by *where you encounter them*. This file is generated from the guard's reason registry, so it can",
    "never drift from the codes actually emitted.",
    "",
    ...sections,
  ].join("\n");

  writeFileSync(OUTPUT, out.replace(/\n+$/, "\n"), "utf8");
  // eslint-disable-next-line no-console
  console.log(`${OUTPUT}: ${codes.length} reason codes documented.`);
}

main();
