// Generate TRACEABILITY.md — the Requirements Traceability Matrix — from REQUIREMENTS.md + the
// actual test-suite results. Run via `npm run traceability` (vite-node). The output is DETERMINISTIC
// (no timestamps/commit hashes), so a CI step can regenerate it and fail if the committed copy is
// stale — the matrix can never silently drift from reality. Do not edit TRACEABILITY.md by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parseRequirements } from "./lib/requirements.js";

const REQUIREMENTS = "REQUIREMENTS.md";
const OUTPUT = "TRACEABILITY.md";

/** Obtain per-test {title → status} from the suite. Reuse an existing JSON report if TRACEABILITY_RESULTS
 *  is set (CI, to avoid double-running vitest); otherwise run the default suite with the JSON reporter. */
function testStatuses(): Map<string, string> {
  let jsonPath = process.env.TRACEABILITY_RESULTS;
  if (!jsonPath) {
    jsonPath = join(tmpdir(), "x402-traceability-results.json");
    try {
      execFileSync("npx", ["vitest", "run", "--reporter=json", "--outputFile", jsonPath], {
        stdio: ["ignore", "ignore", "inherit"],
      });
    } catch {
      // vitest exits nonzero on any failure — the report is still written; read it and report failures.
    }
  }
  const report = JSON.parse(readFileSync(jsonPath, "utf8")) as {
    testResults?: { assertionResults?: { title: string; status: string }[] }[];
  };
  const map = new Map<string, string>();
  for (const file of report.testResults ?? []) {
    for (const a of file.assertionResults ?? []) map.set(a.title, a.status);
  }
  return map;
}

const SYMBOL: Record<string, string> = { passed: "✅", failed: "❌", skipped: "⚠️", missing: "❓" };

/** Shorten a requirement's markdown description to one readable line for the matrix cell. */
function short(desc: string): string {
  const s = desc.replace(/\s+/g, " ").trim();
  if (s.length <= 150) return s;
  const cut = s.slice(0, 150);
  return cut.slice(0, cut.lastIndexOf(" ")) + "…";
}

function main(): void {
  const md = readFileSync(REQUIREMENTS, "utf8");
  const version = (JSON.parse(readFileSync("package.json", "utf8")) as { version: string }).version;
  const reqs = parseRequirements(md);
  const status = testStatuses();

  const tally = { passed: 0, failed: 0, skipped: 0, missing: 0 };
  let verified = 0;
  const rows: string[] = [];
  for (const r of reqs) {
    // Per-test status (missing = named but not found in the run — traceability.test.ts would already fail).
    const perTest = r.tests.map((t) => status.get(t) ?? "missing");
    for (const st of perTest) tally[(st in SYMBOL ? st : "failed") as keyof typeof tally]++;
    const roll = perTest.includes("missing")
      ? "missing"
      : perTest.includes("failed")
        ? "failed"
        : perTest.includes("skipped")
          ? "skipped"
          : "passed";
    if (roll === "passed") verified++;
    const tests = r.tests.map((t) => `\`${t}\``).join(", ") || "—";
    rows.push(`| **${r.id}** | ${short(r.description)} | ${r.threat} | ${tests} | ${SYMBOL[roll]} ${roll} |`);
  }

  const checks = tally.passed + tally.failed + tally.skipped + tally.missing;
  const distinct = new Set(reqs.flatMap((r) => r.tests)).size;

  // Bolded requirement ids that appear in the doc but are NOT verification rows — proposed /
  // pending-ratification requirements with no test yet. Listed so the count is self-explaining.
  const rowIds = new Set(reqs.map((r) => r.id));
  const proposed = [...new Set([...md.matchAll(/\*\*([A-Z]+-\d+)\*\*/g)].map((m) => m[1]))]
    .filter((id) => !rowIds.has(id))
    .sort();

  const out = [
    "# Requirements Traceability Matrix",
    "",
    "<!-- GENERATED by `npm run traceability` from REQUIREMENTS.md + the test suite. DO NOT EDIT BY HAND.",
    "     A CI step regenerates this and fails if it is stale, so it can never drift from reality. -->",
    "",
    `**x402-spendguard \`v${version}\`** — ${reqs.length} verified requirements · ${distinct} tests · ` +
      `${checks} requirement→test checks · **${verified}/${reqs.length} verified** ` +
      `(${tally.passed} passed · ${tally.failed} failed · ${tally.skipped} skipped · ${tally.missing} missing).`,
    "",
    "Each requirement is verified by the named test(s). Their existence is *enforced* by",
    "`test/traceability.test.ts` (the build fails if a named test is missing); their pass/fail status",
    "here is from the suite run. **Verified** = every named test exists and passed. A test may verify",
    "more than one requirement, so *checks* ≥ *tests*.",
    "",
    "| Requirement | Description | Threat | Verified by | Status |",
    "|-------------|-------------|--------|-------------|--------|",
    ...rows,
    "",
    ...(proposed.length
      ? [
          `> **Proposed (not yet ratified — no test, excluded from the count above):** ${proposed
            .map((id) => `\`${id}\``)
            .join(", ")}. See REQUIREMENTS.md / docs/roadmap.md.`,
          "",
        ]
      : []),
  ].join("\n");

  writeFileSync(OUTPUT, out, "utf8");
  // eslint-disable-next-line no-console
  console.log(`${OUTPUT}: ${verified}/${reqs.length} requirements verified (${tally.failed} failed, ${tally.missing} missing).`);
  if (tally.failed > 0 || tally.missing > 0) process.exitCode = 1;
}

main();
